import { Link } from 'react-router-dom';

export default function LegalPage() {
  return <div className="max-w-4xl mx-auto px-6 py-12">
    <Link to="/" className="text-primary underline">Back to the club</Link>
    <header className="my-8"><h1 className="font-display text-3xl sm:text-5xl text-ink">Terms and Conditions</h1><p className="text-sm text-ink-variant mt-3">Last updated: 28 September 2026</p></header>
    <section className="py-6 border-t border-outline-variant/40"><h2 className="font-display text-xl text-ink mb-3">1. Using the platform</h2><p className="text-ink-variant leading-relaxed">These terms cover QIU Sports Club, an unofficial student-run club website. By using the site you agree to these terms. If you do not agree, stop using the site. Optional analytics is a separate choice and is not required to browse public content.</p></section>
    <section className="py-6 border-t border-outline-variant/40"><h2 className="font-display text-xl text-ink mb-3">2. What the site provides</h2><p className="text-ink-variant leading-relaxed">The site publishes club articles, profiles, tournament schedules, match results, standings, and sports statistics. It also provides administration tools for authorised accounts. It is not an official statement or service of Qaiwan International University or Universiti Teknologi Malaysia.</p></section>
    <section className="py-6 border-t border-outline-variant/40"><h2 className="font-display text-xl text-ink mb-3">3. Public and restricted access</h2><p className="text-ink-variant leading-relaxed">Visitors can browse published club content, tournament information, results, and public team summaries. Account-only areas and administrator actions require the appropriate access. Analytics reports, draft articles, and internal player notes are not public. Public match and tournament information may include participant names and photos.</p></section>
    <section className="py-6 border-t border-outline-variant/40"><h2 className="font-display text-xl text-ink mb-3">4. Account and editorial responsibilities</h2><p className="text-ink-variant leading-relaxed">Keep credentials confidential and notify the administrators if you suspect unauthorised access. Administrators must check the accuracy of results and articles, have permission to publish photos and personal information, respect copyright, and avoid publishing unnecessary private information. Use extra care and obtain appropriate permission for content involving minors. Only authorised administrators may manage content or view audience reports.</p></section>
    <section className="py-6 border-t border-outline-variant/40"><h2 className="font-display text-xl text-ink mb-3">5. Acceptable use</h2><p className="text-ink-variant leading-relaxed">Do not attempt unauthorised access, interfere with the service, overload its endpoints, harvest personal information, impersonate participants, manipulate scores, or fabricate analytics activity. Automated bulk collection and security testing require the operator's permission. Report suspected vulnerabilities privately to the administrator.</p></section>
    <section className="py-6 border-t border-outline-variant/40"><h2 className="font-display text-xl text-ink mb-3">6. Results and analytics</h2><p className="text-ink-variant leading-relaxed">Fixtures and results may change or need correction; consult the club organisers for authoritative competition decisions. Analytics describes consenting browser activity, not exact numbers of people. Blockers, missing referrals, shared devices, bots, and incomplete periods can affect counts. Analytics is intended for internal editorial and service improvements.</p></section>
    <section className="py-6 border-t border-outline-variant/40"><h2 className="font-display text-xl text-ink mb-3">7. Content and intellectual property</h2><p className="text-ink-variant leading-relaxed">Names, logos, photos, articles, and other materials remain subject to their owners' rights. Viewing public content does not transfer those rights. Ask permission before redistributing images or substantial articles. Contact the administrators about inaccurate content, unauthorised photos, or copyright concerns.</p></section>
    <section className="py-6 border-t border-outline-variant/40"><h2 className="font-display text-xl text-ink mb-3">8. Availability and responsibility</h2><p className="text-ink-variant leading-relaxed">The platform is provided as available. We aim to maintain accurate content and reliable access but cannot promise uninterrupted operation, complete accuracy, or freedom from every security issue. To the extent permitted by applicable law, the operator is not responsible for losses caused by service interruptions or reliance on inaccurate information. Nothing in these terms excludes rights or liabilities that cannot lawfully be excluded.</p></section>
    <section className="py-6 border-t border-outline-variant/40"><h2 className="font-display text-xl text-ink mb-3">9. Access changes and updates</h2><p className="text-ink-variant leading-relaxed">We may restrict abusive access, remove inappropriate material, correct errors, or change features. These terms may be updated, with the revision date shown above. The Privacy Policy explains data processing and analytics choices. Any applicable legal rights continue to apply.</p></section>
    <section className="py-6 border-t border-outline-variant/40"><h2 className="font-display text-xl text-ink mb-3">10. Contact</h2><p className="text-ink-variant leading-relaxed">For support, corrections, permission requests, or privacy concerns, contact the club through the Instagram link in the footer or the administrator at halangame4@gmail.com.</p></section>
    <p className="mt-8"><Link className="text-primary underline" to="/privacy">Privacy Policy</Link></p>
  </div>;
}
